### ISSUE TITLE
Documentation: Clarify behavior of -M switch with multiple URLs

### ISSUE THREAD

**Issue by thaljef** [briandfoy/cpan-script#4]
Perhaps I'm just too accustomed to working with DarkPANs, but I think most people expect that multiple mirror URLs means each mirror will be searched for any given package (this is what `cpanm` does).  

But that has never been the case for `CPAN.pm.`  It merely uses the list to find a mirror that is alive.  Once it has an index from one of those mirrors, it doesn't bother searching on the other mirrors.

There are valid use cases for both behaviors, so I'm not suggesting that one or the other is "right".   But I think it is worth clarifying in the documentation.

**Comment by briandfoy** [comment]
I'm shutting down this repo. I'm closing this but that has nothing to do with the merits of this issue.
